--- 
abstract: a simple interface for QQWry IP database(file).
author: sunnavy  C<< <sunnavy@gmail.com> >>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.650
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: IP-QQWry
no_index: 
  directory: 
    - inc
    - t
requires: 
  perl: 5.8.0
  version: 0
version: !!perl/hash:version 
  qv: 1
  version: 
    - 0
    - 0
    - 15
