---
abstract: 'a simple interface for QQWry IP database(file).'
author:
  - 'sunnavy  C<< <sunnavy@gmail.com> >>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.19'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: IP-QQWry
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  perl: 5.8.0
  version: 0
resources:
  license: http://dev.perl.org/licenses/
version: '0.000021'
